### ISSUE TITLE
User's aren't logged in even with correct credentials

### ISSUE THREAD

**Issue by djperrefort** [pitt-crc/keystone-web#54]
An alert for incorrect credentials is shown despite the username/password being correct.

**Comment by Comeani** [comment]
Currently investigating whether this is related to the way tokens are being refreshed.

**Comment by Comeani** [comment]
So I think I've figured out whats going on:

https://github.com/pitt-crc/keystone-web/blob/73056507df2abfd71cd5b2f29dd021e507329e5a/src/app/core/services/api.service.ts#L188

```
const accessTokenExpired: boolean = !!this.accessTokenExpiration && Date.now() < this.accessTokenExpiration;
    if (!accessTokenExpired) {
      return;
    }
```
`this.accessTokenExpiration` is either the milisecond timestamp corresponding to the expiration time, or `null` if an access token is not present. 

If there is no access token yet, `this.accessTokenExpiration` is `null`, `Date.now() < this.accessTokenExpiration` is `false`, so this.accesstokenExpired is `null` and the conditional is entered. 

I think the intention was to do nothing if the access token was _not_ expired. 
In that this just returns without refreshing whether there is an access token or not, the refresh mechanism is never reached, even when it needs to be.

Working on a PR now to fix this.
